#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later
#
# ============================================================================
# WARNING: THIS FILE WAS GENERATED OR SUBSTANTIALLY EDITED BY GITHUB COPILOT
# FOLLOWING DIRECT USER INSTRUCTIONS.
#
# It is intended to be safe and functional and is not expected to cause
# issues, but it may still contain mistakes, omissions, edge-case bugs, or
# plain bad calls.
#
# If you are cautious or suspicious, review this file closely. If you find
# anything fishy, incorrect, risky, or unclear, please open an issue or submit
# a pull request with the fix.
# ============================================================================

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/.." && pwd)"
version="$(tr -d '\n' < "${repo_root}/VERSION")"
package_name="obs-snekstudio-source"
archive_root="${package_name}-${version}"
dist_dir="${repo_root}/dist"
archive_path="${dist_dir}/${archive_root}.tar.gz"

mkdir -p "${dist_dir}"

tar \
	-C "${repo_root}" \
	--exclude='./.venv' \
	--exclude='./.vscode' \
	--exclude='./build' \
	--exclude='./dist' \
	--exclude='./stage' \
	--exclude='./packaging/arch/src' \
	--exclude='./packaging/arch/pkg' \
	--exclude='./packaging/arch/*.pkg.tar.zst' \
	--exclude='./packaging/arch/*.pkg.tar.zst.sig' \
	--exclude='./packaging/arch/*.tar.gz' \
	--exclude='./packaging/arch/.SRCINFO' \
	--exclude='./__pycache__' \
	--transform "s,^\./,${archive_root}/," \
	-czf "${archive_path}" \
	.

echo "Created ${archive_path}"
sha256sum "${archive_path}"